verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 3.0.0

dependencies:
  - QuickCheck
  - base >= 4.9 && < 5
  - bytestring
  - cardano-api
  - cardano-crypto
  - cardano-ledger-shelley
  - cardano-node-emulator
  - containers
  - data-default
  - either
  - flat
  - list-t
  - monad-control
  - mtl
  - nonempty-containers
  - optics-core
  - optics-th
  - plutus-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-script-utils
  - plutus-tx
  - plutus-tx-plugin
  - prettyprinter
  - random
  - random-shuffle
  - strict-sop-core
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - text
  - transformers

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-missed-extra-shared-lib
    -fobject-code
    -fno-ignore-interface-pragmas
    -fignore-hpc-changes
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors
    -fplugin-opt PlutusTx.Plugin:conservative-optimisation
  default-extensions:
    - ImportQualifiedPost
    - AllowAmbiguousTypes
    - ConstraintKinds
    - DataKinds
    - DerivingStrategies
    - DerivingVia
    - ExtendedDefaultRules
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - LambdaCase
    - MultiParamTypeClasses
    - NamedFieldPuns
    - NumericUnderscores
    - OverloadedStrings
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - StrictData
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - TypeSynonymInstances
    - ViewPatterns

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/
    ghc-options:
      -Wall
      -Wno-missed-extra-shared-lib
      -Wno-type-defaults
      -fobject-code
      -fno-ignore-interface-pragmas
      -fignore-hpc-changes
      -fno-omit-interface-pragmas
      -fplugin-opt PlutusTx.Plugin:defer-errors
      -fplugin-opt PlutusTx.Plugin:conservative-optimisation
    dependencies:
      - cooked-validators
      - parsec
    default-extensions:
      - ImportQualifiedPost
      - DataKinds
      - ExtendedDefaultRules
      - FlexibleContexts
      - FlexibleInstances
      - GADTs
      - LambdaCase
      - MultiParamTypeClasses
      - MultiWayIf
      - NumericUnderscores
      - OverloadedStrings
      - RankNTypes
      - ScopedTypeVariables
      - TemplateHaskell
      - TupleSections
      - TypeApplications
      - TypeFamilies
      - ViewPatterns
