verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 9.0.0
    
library:
  source-dirs: src
  dependencies:
    - QuickCheck
    - base >= 4.9 && < 5
    - bytestring
    - cardano-api
    - cardano-crypto
    - cardano-ledger-core
    - cardano-ledger-shelley
    - cardano-ledger-conway
    - cardano-node-emulator
    - cardano-strict-containers
    - containers
    - data-default
    - either
    - exceptions
    - http-conduit
    - lens
    - microlens
    - optics-core
    - optics-th
    - ordered-containers
    - plutus-ledger
    - plutus-ledger-api
    - plutus-script-utils
    - plutus-tx
    - polysemy
    - polysemy-plugin
    - prettyprinter
    - random
    - random-shuffle
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - text
  ghc-options: &ghc-options
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -Wno-missed-extra-shared-lib
    -fobject-code
    -fno-ignore-interface-pragmas
    -fignore-hpc-changes
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors
    -fplugin-opt PlutusTx.Plugin:conservative-optimisation
    -fplugin=Polysemy.Plugin
  default-extensions: &default-extensions
    - ConstraintKinds
    - DataKinds
    - DeriveFunctor
    - DerivingStrategies
    - DerivingVia
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NumericUnderscores
    - OverloadedStrings
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - ViewPatterns

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/
    dependencies:
      - base >= 4.9 && < 5
      - cardano-api
      - containers
      - cooked-validators
      - data-default
      - optics-core
      - plutus-core
      - plutus-ledger
      - plutus-ledger-api
      - plutus-script-utils
      - plutus-tx
      - plutus-tx-plugin
      - polysemy
      - polysemy-plugin
      - prettyprinter
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - text
    ghc-options: *ghc-options        
    default-extensions: *default-extensions
