verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 4.0.0

dependencies:
  - QuickCheck
  - base >= 4.9 && < 5
  - bytestring
  - cardano-api
  - cardano-crypto
  - cardano-data
  - cardano-ledger-alonzo
  - cardano-ledger-core
  - cardano-ledger-shelley
  - cardano-ledger-conway
  - cardano-node-emulator
  - cardano-strict-containers
  - containers
  - data-default
  - either
  - exceptions
  - flat
  - http-conduit
  - lens
  - list-t
  - microlens
  - monad-control
  - mtl
  - nonempty-containers
  - optics-core
  - optics-th
  - plutus-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-script-utils
  - plutus-tx
  - plutus-tx-plugin
  - prettyprinter
  - random
  - random-shuffle
  - strict-sop-core
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - text
  - transformers
    
library:
  source-dirs: src
  ghc-options: &ghc-options
    -Wall
    -Wcompat
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wredundant-constraints
    -Wno-missed-extra-shared-lib
    -fobject-code
    -fno-ignore-interface-pragmas
    -fignore-hpc-changes
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors
    -fplugin-opt PlutusTx.Plugin:conservative-optimisation
  default-extensions: &default-extensions
    - ConstraintKinds
    - DataKinds
    - DerivingStrategies
    - DerivingVia
    - FlexibleContexts
    - FlexibleInstances
    - GADTs
    - GeneralizedNewtypeDeriving
    - ImportQualifiedPost
    - LambdaCase
    - MultiParamTypeClasses
    - MultiWayIf
    - NamedFieldPuns
    - NumericUnderscores
    - OverloadedStrings
    - PolyKinds
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - StandaloneDeriving
    - TemplateHaskell
    - TupleSections
    - TypeApplications
    - TypeFamilies
    - TypeOperators
    - ViewPatterns

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/
    ghc-options: *ghc-options  
    dependencies:
      - cooked-validators
    default-extensions: *default-extensions