verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 0.0.0
extra-source-files:
  - README.md


dependencies:
  - base >= 4.9 && < 5
  - aeson
  - bytestring
  - containers
  - data-default
  - deepseq
  - either
  - flat
  - foldl
  - freer-extras
  - freer-simple
  - lens
  - mtl
  - plutus-contract
  - plutus-core
  - plutus-ledger
  - plutus-ledger-constraints
  - plutus-ledger-api
  - plutus-pab
  - plutus-tx
  - plutus-tx-plugin
  - plutus-use-cases
  - prettyprinter
  - scientific
  - streaming
  - tasty
  - text
  - transformers
  - HUnit
  - QuickCheck
  - quickcheck-transformer

library:
  source-dirs: src
  ghc-options:
    -Wall
    -fobject-code
    -fno-ignore-interface-pragmas
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - tests/
    dependencies:
      - cooked-validators
      - hspec
