verbatim:
  cabal-version: 3.4

name: cooked-validators
version: 0.2.0
extra-source-files:
  - README.md

dependencies:
  - base >= 4.9 && < 5
  - aeson
  - bytestring
  - containers
  - data-default
  - deepseq
  - either
  - flat
  - foldl
  - freer-extras
  - freer-simple
  - lens
  - monad-control
  - mtl
  - plutus-contract
  - plutus-core
  - plutus-ledger
  - plutus-ledger-constraints
  - plutus-ledger-api
  - plutus-script-utils
  - plutus-pab
  - plutus-tx
  - plutus-tx-plugin
  - prettyprinter
  - scientific
  - streaming
  - text
  - transformers
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - QuickCheck
  - cardano-api
  - cardano-crypto
  - cardano-wallet-core
  - memory
  - optics-core
  - optics-vl
  - optics-th
  - hashable
  - hedgehog-quickcheck
  - nonempty-containers

library:
  source-dirs: src
  ghc-options:
    -Wall
    -Wno-missed-extra-shared-lib
    -fobject-code
    -fno-ignore-interface-pragmas
    -fno-omit-interface-pragmas
    -fplugin-opt PlutusTx.Plugin:defer-errors
