name: Runs a command within our nix-shell
description: Runs a command within our nix environment
inputs:
  command:
    required: true
    description: The command to run
runs:
  using: "composite"
  steps:
  - run: nix develop .#ci --command "${{ inputs.command }}"
    shell: bash
