verbatim:
  cabal-version: 3.4

name: examples
version: 0.0.0


dependencies:
  - base >= 4.9 && < 5
  # Internal dependencies of the test suite
  - cooked-validators
  - tasty-twaudit-metadata
  # Other libraries that you will likely need to write a good test-suide:
  - QuickCheck
  - quickcheck-transformer
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - tasty-expected-failure
  - heredoc
  - tasty-hspec # should be removed after rewriting test suite with tasty-hunit and tasty-quickcheck
  # Dependencies of the example contracts, these come from the client
  - aeson
  - bytestring
  - containers
  - data-default
  - either
  - flat
  - foldl
  - freer-extras
  - freer-simple
  - hspec
  - lens
  - mtl
  - playground-common
  - plutus-contract
  - plutus-core
  - plutus-ledger
  - plutus-ledger-api
  - plutus-pab
  - plutus-tx
  - plutus-tx-plugin
  - plutus-use-cases
  - scientific
  - serialise >= 0.2.3.0
  - streaming
  - text
  - transformers

library:
  source-dirs: src
  ghc-options:
    -Wall 
    -fobject-code 
    -fno-ignore-interface-pragmas 
    -fno-omit-interface-pragmas

tests:
  spec:
    source-dirs: tests
    main: Spec.hs
    dependencies:
      - examples
