-- | This module exposes the various events emitted during a mockchain run.
module Cooked.Runtime.Journal
  ( ChainJournal (..),
    fromLogEntry,
    fromAlias,
    fromNote,
    fromAssert,
  )
where

import Cooked.Effect.Log
import Cooked.Pretty.Class
import Cooked.Pretty.Options
import Data.Map
import Data.Map qualified as Map
import PlutusLedgerApi.V3 qualified as Api

-- | This represents the writable elements that can be emitted throughout a
-- mockchain run.
data ChainJournal where
  ChainJournal ::
    { -- | Log entries generated by cooked-validators
      mcbLog :: [MockChainLogEntry],
      -- | Aliases stored by the user
      mcbAliases :: Map Api.BuiltinByteString String,
      -- | Notes taken by the user, parameterized by some pretty cooked options,
      -- to get a better display at the end of the run
      mcbNotes :: [PrettyCookedOpts -> DocCooked],
      -- | Assertions gathered during the run, alongside their associated error
      -- messages to display in case of failure
      mcbAssertions :: [(PrettyCookedOpts -> DocCooked, Bool)]
    } ->
    ChainJournal

instance Semigroup ChainJournal where
  ChainJournal l a n p <> ChainJournal l' a' n' p' =
    ChainJournal (l <> l') (a <> a') (n <> n') (p <> p')

instance Monoid ChainJournal where
  mempty = ChainJournal mempty mempty mempty mempty

-- | Build a `ChainJournal` from a single log entry
fromLogEntry :: MockChainLogEntry -> ChainJournal
fromLogEntry entry = mempty {mcbLog = [entry]}

-- | Build a `ChainJournal` from a single alias
fromAlias :: String -> Api.BuiltinByteString -> ChainJournal
fromAlias s hash = mempty {mcbAliases = Map.singleton hash s}

-- | Build a `ChainJournal` from a single note
fromNote :: (PrettyCookedOpts -> DocCooked) -> ChainJournal
fromNote s = mempty {mcbNotes = [s]}

-- | Build a `ChainJournal` from a single assertion and error message
fromAssert :: (PrettyCookedOpts -> DocCooked) -> Bool -> ChainJournal
fromAssert s p = mempty {mcbAssertions = [(s, p)]}
