-- | This module exposes the various events emitted during a mockchain run.
module Cooked.Runtime.Journal
  ( TxValidity (..),
    ChainLogEntry (..),
    ChainJournal (..),
    fromLogEntry,
    fromAlias,
    fromNote,
    fromAssert,
  )
where

import Cooked.Pretty.Class
import Cooked.Pretty.Options
import Cooked.Skeleton
import Cooked.Utilities.Aliases
import Data.Map
import Data.Map qualified as Map
import Plutus.Script.Utils.Scripts qualified as Script
import PlutusLedgerApi.V3 qualified as Api

-- | The validity of a transaction
data TxValidity
  = -- | The transaction is valid, we store the number of inputs and outputs
    Valid Int Int
  | -- | The transaction is invalid in phase 1 (no ledger change)
    InvalidPhase1
  | -- | The transaction is invalid in phase 2, we store the number of collateral
    -- inputs and return collateral outputs
    InvalidPhase2 Int Int
  deriving (Show)

-- | Events logged when processing transaction skeletons
data ChainLogEntry
  = -- | Logging a Skeleton as it is submitted by the user.
    CLogSubmittedTxSkel TxSkel
  | -- | Logging a Skeleton as it has been adjusted by the balancing mechanism,
    -- alongside fee, and possible collateral utxos and return collateral user.
    CLogAdjustedTxSkel TxSkel Fee (Maybe Collaterals)
  | -- | Logging the production of a new transaction, with its ID as well as its
    -- validity.
    CLogNewTx Api.TxId TxValidity
  | -- | Logging the fact that utxos provided by the user for balancing have to be
    -- discarded for a specific reason.
    CLogDiscardedUtxos Integer String
  | -- | Logging the fact that utxos provided as collaterals will not be used
    -- because the transaction does not involve scripts. There are 2 cases,
    -- depending on whether the user has provided an explicit user or a set of
    -- utxos to be used as collaterals.
    CLogUnusedCollaterals (Either Peer CollateralIns)
  | -- | Logging the automatic addition of a reference script
    CLogAddedReferenceScript TxSkelRedeemer Api.TxOutRef Script.ScriptHash
  | -- | Logging the automatic addition of a withdrawal amount
    CLogAutoFilledWithdrawalAmount Api.Credential Api.Lovelace
  | -- | Logging the automatic addition of the constitution script
    CLogAutoFilledConstitution Api.ScriptHash
  | -- | Logging the automatic adjustment of a min ada amount
    CLogAdjustedTxSkelOut TxSkelOut Api.Lovelace
  | -- | Logging the existence of failures uncovered during the computation of
    -- execution units, when they're not treated as fatal.
    CELogExUnitsFailures ExUnitsFailures
  | -- | Logging the existence of failures uncovered during submission, when
    -- they're not treated as fatal.
    CELogSubmissionFailures SubmissionFailures
  deriving (Show)

-- | This represents the writable elements that can be emitted throughout a
-- mockchain run.
data ChainJournal where
  ChainJournal ::
    { -- | Log entries generated by cooked-validators
      mcbLog :: [ChainLogEntry],
      -- | Aliases stored by the user
      mcbAliases :: Map Api.BuiltinByteString String,
      -- | Notes taken by the user, parameterized by some pretty cooked options,
      -- to get a better display at the end of the run
      mcbNotes :: [PrettyCookedOpts -> DocCooked],
      -- | Assertions gathered during the run, alongside their associated error
      -- messages to display in case of failure
      mcbAssertions :: [(PrettyCookedOpts -> DocCooked, Bool)]
    } ->
    ChainJournal

instance Semigroup ChainJournal where
  ChainJournal l a n p <> ChainJournal l' a' n' p' =
    ChainJournal (l <> l') (a <> a') (n <> n') (p <> p')

instance Monoid ChainJournal where
  mempty = ChainJournal mempty mempty mempty mempty

-- | Build a `ChainJournal` from a single log entry
fromLogEntry :: ChainLogEntry -> ChainJournal
fromLogEntry entry = mempty {mcbLog = [entry]}

-- | Build a `ChainJournal` from a single alias
fromAlias :: String -> Api.BuiltinByteString -> ChainJournal
fromAlias s hash = mempty {mcbAliases = Map.singleton hash s}

-- | Build a `ChainJournal` from a single note
fromNote :: (PrettyCookedOpts -> DocCooked) -> ChainJournal
fromNote s = mempty {mcbNotes = [s]}

-- | Build a `ChainJournal` from a single assertion and error message
fromAssert :: (PrettyCookedOpts -> DocCooked) -> Bool -> ChainJournal
fromAssert s p = mempty {mcbAssertions = [(s, p)]}
